spring.datasource.url=jdbc:mysql://localhost:3306/nutrifit_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=nutrifit_user
spring.datasource.password=nutrifit_pass
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
nutrifit.app.geminiApiKey=${GEMINI_API_KEY}
nutrifit.app.jwtSecret=CokGizliAnahtarKelimesiBurayaYazilmalidir2026
nutrifit.app.jwtExpirationMs=86400000